config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:index, :create]
    resources :chat, only: [:show, :update, :destroy] # 質問 resourceに出来ないのか？
    get 'follows', 'followers'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get '*anything' => 'homes#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # favoritesのデータベースに存在するuser_idカラムの各値が、
  # 引数として渡されたuserのidと一致するかどうかを調べてる。

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
  # 空白の保存を禁止にする
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  # belongs_to :follower, class_name: "User", :foreign_key => 'follower_id'
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  # belongs_to :followed, class_name: 'User', :foreign_key => 'followed_id'

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages
  has_many :user_rooms
  has_many :users, through: :user_rooms
  # Roomモデルは、user_roomを経由して(用いて)、userにアクセス出来る。
  # room.userでユーザー一覧を引っ張れる。

end

app/models/serach.rb
class Serach < ApplicationRecord

  def self.search(method, word, target)

    if target == 'target_user'
      target = User
      column = 'name'
    end

    if target == 'target_book'
      target = Book
      column = 'title'
    end

    unless target == nil

      if method == "forward_match"
        @posts = target.where("#{column} like ?","#{word}%") # 質問 whereで二つのカラムを対象に検索する事は出来るのか？
      elsif method == "backward_match"
        @posts = target.where("#{column} like ?","%#{word}")
      elsif method == "perfect_match"
        @posts = target.where("#{column} like ?","#{word}")
      elsif method == "partial_match"
        @posts = target.where("#{column} like ?","%#{word}%")
      else
        @posts = target.all
      end

    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, presence: true, on: :update # 質問
  validates :introduction, length: { maximum: 50 }

  # ここ以下、課題7で追加した内容
  include JpPrefecture
  jp_prefecture :prefecture_code
  # ↑ 都道府県コードから都道府県名に自動で変換する。

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # ↑2つ、
  # ~.prefecture_nameで都道府県名を参照出来る様にする。
  # 例) @user.prefecture_nameで該当ユーザーの住所(都道府県)を表示出来る。

  # ここ以上、課題7で追加した内容

  with_options presence: true, on: :create do
  validates :postcode
  end

  # 以下課題9で設定

  has_many :chats
  has_many :user_rooms
  has_many :rooms, through: :user_rooms

  # 以上課題9で設定

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :room_id, uniqueness: { scope: :user_id }
  # ユーザーの情報とルームはレコードごとに被ることはないように一意の制約をかける

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_book, only: [:update, :edit]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @on_favorites = true
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      flash[:alert] = 'メッセージを入力してください。'
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :chats_maker

  def show
    @master = User.find(params[:user_id])
    @new_chat = Chat.new
  end

  def update
    @master = User.find(params[:user_id])
    Chat.create(message: params[:chat][:message], user_id: current_user.id, room_id: @room_num)
    @new_chat = Chat.new
    render 'chat_add'
  end

  private

    def chat_params
      params.require(:chat).permit(:message)
    end
    # 質問 この辺の記述が冗長過ぎる？
    def chats_maker
      trigger = true
      if my_user_room = UserRoom.where(user_id: current_user.id)
        if you_user_room = UserRoom.where(user_id: params[:user_id])
        @room_num = (my_user_room.pluck(:room_id) & you_user_room.pluck(:room_id)).join.to_i
        unless @room_num == 0
          @chats = Chat.where(room_id: @room_num)
          trigger = false
          end
        end
      end
      if trigger
        fast_contact
      end
    end

    def fast_contact
      room = Room.create
      UserRoom.create(room_id: room.id, user_id: params[:user_id])
      UserRoom.create(room_id: room.id, user_id: current_user.id)
      chats_maker
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="pb-3">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="text-primary mt-2">
    <p class="flash-message text-success mb-1"><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="text-danger mt-2">
    <p class="flash-message text-error mb-1"><%= flash[:alert] %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to ' Books',books_path ,class: 'fas fa-book-open nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light', data: {"turbolinks" => false}  %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-task9</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <% if user_signed_in? %>
      <%= render 'search/search' %>
    <% end %>

    <main>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <p id="notice"><%= notice %></p>
        </div>
      </div>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

  </body>

</html>